### ISSUE TITLE
Select Images For Raking UI

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#10]
The title in in flow with the check boxes

**Comment by thanneken** [comment]
The latest build fixed the problem of showing the full paths. 

It still requires horizontal scrolling. Two UI ideas:

1. Replace not only the filepath but also the constant portion of the filename with ellipsis. For example, in my data each option begins `Ambrosiana_C73inf_062_RTI-` and only the information thereafter is relevant. This is a common practice.

2. Draw a wider dialog menu. I think we can assume at least a HD display for anyone using this.

**Comment by thehabes** [comment]
Definitely an overall principle brought to light here.  Make the dialogs form to a large percentage of the detected screen size instead of hard coding values.  This will give the dialog space where the screen can accommodate it.

**Comment by thehabes** [comment]
This is now working, but needs UI review and will be tracked there.
