### ISSUE TITLE
Filename appearance preference

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#11]
Implement a preference for how file names show in the various popups.  If the user selects the short name, don't include the file path, just show the file name.

**Comment by thehabes** [comment]
When shortened filenames appear, have a 'click to show full name' functionality attached to them.

**Comment by thehabes** [comment]
include an ellipse at the beginning to infer there is more to the name.

**Comment by thanneken** [comment]
This seems like a good idea but I'm not seeing any short filenames or options to that effect.
