### ISSUE TITLE
Custom Dialogs don't have maximize

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#12]
There is no maximize button on the new custom dialogs.

**Comment by thehabes** [comment]
In short, JOptionPane which are the dialogs you see do not take a Java Window or subset of Window (which are the things that have maximize).  Essentially, best practice with Java says these windows SHOULD NOT have a maximize feature and in fact the type of window for this specific process SHOULD NOT maximize.  To offer a maximize button, we would have to hack the best practice implemented through the class, which we SHOULD NOT.

https://stackoverflow.com/questions/3897927/java-modal-window-with-maximize-button

**Comment by thanneken** [comment]
This seems fine to me.
