### ISSUE TITLE
Investigate Viewers

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#3]
See what viewers work and how they work with the RTI files output by this process.

**Comment by thehabes** [comment]
Universal Viewer, WebRIT, ...

**Comment by thanneken** [comment]
http://culturalheritageimaging.org/What_We_Offer/Downloads/View/index.html
Also works in Wine on Linux.

**Comment by thehabes** [comment]
We have successfully put a demo up.  You can view a WebRTI file here:

https://centerfordigitalhumanities.github.io/RTI-Demo/?directory=sample4&width=900&height=600
