### ISSUE TITLE
projDir/PCA/

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#42]
This never appears to be written to.  It is for "opening pregenerated images" but there are never any there.  Confirmed that the macro does not appear to write to these folder either, there is only a read request.  How is this folder supposed to be populated?  Manually by the user or automatically at some point by the code when running PCA?

**Comment by thanneken** [comment]
That sounds right that it is not written to. I believe it is only used if the user selects PCA and then "Open pre-generated." It might be a few less clicks than custom process, but not substantially different.

**Comment by thehabes** [comment]
Great, thanks for answering.
