### ISSUE TITLE
Multiplication Value UI

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#43]
This happens when a user chooses to "multiply all images by a fixed value" in the brightness adjustment. 
 Using the imageJ `Multiply...` command results in needing to ask the user for a value twice.  What we want is a custom window where the user sees a preview, but upon submission the value is used from that window without calling up another one.  It would require a custom built image frame and pop up with a custom built preview functionality to pull off, but it would be a lot cleaner.

**Comment by Domhnall101** [comment]
This needs a custom window. The double ok is misleading and confusing. Should be single window with apply button not OK button .Possibly add a slider to the multiply value of practicable

**Comment by thehabes** [comment]
We have settled on the UI.
