### ISSUE TITLE
Zero-length jp2 files in StaticRaking

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#46]
Testing on Linux...
generated static raking files: Ambrosiana_C73inf_114_Ac_00.jp2, Ambrosiana_C73inf_114_Ac_02.jp2, Ambrosiana_C73inf_114_Ac_07.jp2, Ambrosiana_C73inf_114_Ac_51.jp2, Ambrosiana_C73inf_114_Ac_55.jp2, Ambrosiana_C73inf_114_Xs_00.jp2, Ambrosiana_C73inf_114_Xs_02.jp2, Ambrosiana_C73inf_114_Xs_07.jp2, Ambrosiana_C73inf_114_Xs_51.jp2, Ambrosiana_C73inf_114_Xs_55.jp2

Ac_00 was fine, but all the others were zero-length files.
The fact that it works fine for one makes me think it is not a problem with kdu_compress. 
There is nothing helpful in the log or console:
```
[Tue May 29 11:27:11 CDT 2018] [INFO] [] Save ACRaking source image /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_114/StaticRaking/Ambrosiana_C73inf_114_Ac_01.tiff
[Tue May 29 11:27:11 CDT 2018] [INFO] [] Created JP2 /new/JP2file
[Tue May 29 11:27:11 CDT 2018] [INFO] [] Remove ACRaking source image /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_114/StaticRaking/Ambrosiana_C73inf_114_Ac_01.tiff
```
Perhaps the next thing to do is recreate the exact tiff file and kdu_compress command used and see if kdu_compress or bash give a helpful error message.

**Comment by thehabes** [comment]
This is a bit odd.  I have put some better logging around it, it may reveal some clues.  I'll look further into this.

**Comment by thehabes** [comment]
Passing on windows 7, if it breaks on linux still the logs should be more helpful

**Comment by thanneken** [comment]
Works on Linux
