### ISSUE TITLE
Tasks Dialog First

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#54]
The task dialog where a user chooses what to perform should be first.  That way, we know what preferences are required when going forward.  This is related to improving the Preferences gathering process.

**Comment by Domhnall101** [comment]
We need to highlight the required material for each process so we can stall the user until they provide the needed items and they know what they need to provide.

**Comment by Domhnall101** [comment]
See ticket #55 for this

**Comment by thehabes** [comment]
This was taken care of in the UI redo.
