### ISSUE TITLE
ACRTI + ACStaticRaking

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#63]
When i ran both tasks in the same session and had deferred batch as my preferred fitter, it only ran the ACRTI processing.  This may be related to the order of operations described in #37.  This requires further investigation.

**Comment by thehabes** [comment]
hmm.  keep an eye out for this, not sure what happened but I can't make it happen again.

**Comment by thanneken** [comment]
I saw this at one point but it has been fixed. I believe the kdu_compress failed, but it did create the tif. Maybe at some point we can add error catching to notice if kdu_compress fails, but I wouldn't call it a priority at this point.
