### ISSUE TITLE
Override missing path crash cases

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#64]
Instead of crashing out when looking for a required path (like for a prefs file or fitter file), hold these states in a while() loop until a valid path is provided.  

Where this handling takes place is dependent on #36 where me may choose to do all of this interaction at the beginning.

**Comment by Domhnall101** [comment]
Where we can we have to bring the user back to the point where they accidentally drop out of the process. Moving usr input to upfront will alleviate a lot fo this but it remains possible for such events to occor and we should drop them back to the last point where something successful happened

**Comment by thehabes** [comment]
There are a few of these that slip through the cracks and won't be handled in a #36 scenario.  They are secondary level prompts that only ask the user for something based on a choice later down the road.  These prompts cleanly fit into the while() loop idea though and wouldn't be expected to be available in the #36 scenario anyway.

**Comment by thehabes** [comment]
Fixed through the UI and processing redo
