### ISSUE TITLE
Select Transmissive Source Radios in wrong order

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#65]
Same problem as for the other popup, the array needs to be ordered before handing it to the Dialog builder.

**Comment by thehabes** [comment]
Found arrays and added a sort() to them.

**Comment by thanneken** [comment]
Sounds good. As long as the user selection and the actual file used are the same, the visual appearance of this list is not so important because it is always short.
