### ISSUE TITLE
PCA generate and manually select two UI

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#66]
We could add a button to the window that ran the "Delete Slice" command for them.  Then they don't have to use the menu.

We also need to customize what happens when the user clicks "OK".  If there stack is greater than two, they need to be prompted to continue to delete.  If it moves on, there is a crash "Conversion supported for GRAY8 stacks with three slices".  this is because if the user leaves more than 2 in the stack, there are greater than 3 slices.

**Comment by Domhnall101** [comment]
Window should have
current image count, Next/Previous button. delete button and done/finished button

**Comment by thanneken** [comment]
Finally got to see this for the first time without a null pointer exception standing in my way... Two concerns:

A small UI issue: I think the "Previous" should be on the left and the "Next" should be to the right of that (don't care if delete is in the middle or the right end). This is consistent with the ImageJ UI. 

More pressing... The "Delete Slices" window prevents the user from manipulating the image or using the main UI. The user needs to be able to zoom, pan, draw a region of interest, and enhance contrast. In the macro language there is a distinction between a dialog that monopolized attention and one that didn't. I hope it is easy in Java.

**Comment by thehabes** [comment]
I am happy to move buttons around, that is a quick fix.

I should be able to discern between the types of popovers using java.  If it becomes too complicated, we can go back to the one that was there before.  I will investigate.

**Comment by thehabes** [comment]
Thanks for the feedback, we have settled on the UI.
