### ISSUE TITLE
Custom Process: jpeg filenames written to disk should be identical written to lp file

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#68]
The custom process created files such as:
`/media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/KTK01RTI/Ambrosiana_C73inf_115_RTI-A01_043.jpg`
The lp file lists files such as: 
`/media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/KTK01RTI/KTK01_Ambrosiana_C73inf_115_RTI-A01_043.jpg 0.17889495 -0.9825294 0.05130836`
The preferred solution is to begin the filename with the process name (KTK01_). I.e., the format that appears in the lp file is preferable.

**Comment by thehabes** [comment]
Will do, I tried to put some of these things to variables instead of hard coding, I must not have stayed consistent.  Good catch.

**Comment by thehabes** [comment]
Found the variable storing the file path and made sure to add `csProcessName+"_"` to the naming convention.

**Comment by thanneken** [comment]
Confirmed on Linux
