### ISSUE TITLE
WebRTI option also requires a little html to be written

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#69]
It's short and simple if it is done at the same time that the webrti maker command is written/executed.

**Comment by thehabes** [comment]
It should be writing an `wrti.html` file into the `projectDirectory+colorProcess+"RTI"` directory.  It needs a check for if the directory exists since we separated it from the RTI task choice dependency, which may be why you noticed html was not written.  I added this check, it should create this file for you now.

**Comment by thanneken** [comment]
Still not seeing any html files.

**Comment by thehabes** [comment]
Checked it for Accurate Color RTI and Custom Source RTI, they produced the html files on Windows 7 with the fix.

Procedure was to select the Accurate Color RTI task and WebRTI task for the AC test.
Procedure was to select the Custom RTI and WebRTI task for the CS test.
Procedure was to only select WebRTI and provide an already created RTI file for the solo test.

This produced the following html files
/AccurateColorRTI/Ambrosiana_C73inf_115_AccurateColorRTI_20180605_0946_wrti.html
/KTK01RTI/Ambrosiana_C73inf_115_KTK01RTI_20180605_1001_wrti.html
/KTK01RTI/Ambrosiana_C73inf_115_KTK01RTI_20180605_1024_wrti.html

and when opened in a code editor they had the html source.

See if it is working for you.

**Comment by thanneken** [comment]
The bad news is that there is still no html file after running in Linux. The good news is that I think I found the problem. The .txt file has the expected record of settings used, then it has the expected html appended as the last line. I'm not sure why it would pass on Windows but not Linux, but it sounds like a filehandle mix up or uncaught failure to open a filehandle for writing.

**Comment by thehabes** [comment]
See #87 and see if this is still occurring.

**Comment by thanneken** [comment]
Okay now... other than small bug noted in the issue about txt and html files.
