### ISSUE TITLE
Must draw rectangle to continue, can't draw rectangle

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#71]
I tested the "Generate LP file" functionality. 
It got stuck on "You must draw a rectangle to continue" but I couldn't draw a rectangle. 
I recall in the macro language there was a distinction between a prompt that demanded attention and a prompt that allowed the user to do things. 

Not a big deal, but it would be a legitimate application to only generate an LP file and not run the other processes. When I tried to do that it told me I had to select at least one task.

**Comment by thehabes** [comment]
Interesting. I will have to switch dialog types if so.  

For reference, he code that determines that flag is
```java
if(!(acRakingDesired || acRtiDesired || xsRtiDesired || xsRakingDesired || psRtiDesired || psRakingDesired || csRtiDesired || csRakingDesired)){
                if(webRtiDesired){ 
                    /**
                     * If this is the only option selected, allow the user to tell us where the RTI image is for processing
                     */
                    OpenDialog rti_image = new OpenDialog("Locate RTI image to make into WebRTI.");
                    String rtiImageToUse = rti_image.getPath();
                    createWebRTIFiles("", rtiImageToUse);
                }
                else{
                    IJ.error("You must provide at least one task.");
                    throw new Throwable("You must provide at least one task set to continue.");
                 }
            }
```

We can probably add `lpDesired` to that `if(!())` piece unless it needs to be handled separately like `webRtiDesired`

**Comment by thehabes** [comment]
Did not call the `WaitForUserDialog.show()` function, so there is never a process started to let you draw one.  Made sure to `dWait.show()`.

**Comment by thanneken** [comment]
Confirmed on Linux
