### ISSUE TITLE
Custom Process: Writing a monochrome jpeg and a color jpeg

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#72]
For each light position in Custom Process the plugin is writing a monochrome jpeg, then renaming that with a timestamp, then writing a RGB jpeg file that seems to be right. We only need the RGB version.

**Comment by thehabes** [comment]
There is an extra saved called in there when an image was duplicated.  Nothing needs to be saved to disk here, just grabbed and stored to an image variable.

**Comment by thanneken** [comment]
Now it seems to be writing only the monochrome and not the color. Should be the other way...

**Comment by thehabes** [comment]
Alright, I did a rewrite of this piece off the macro because it was a bit off.  It should now be performing the same file saves as the macro, let me know if it is doubling up or forgetting one still.  I ran them side by side and the custom process output looks to be the same.

**Comment by thanneken** [comment]
Confirmed on Linux
