### ISSUE TITLE
Directions/Tooltip/Hints review

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#82]
Now that we wrangled custom windows and almost everything is a custom element, it was easy to supply extra directions and tooltips all over the place.  Some places may be lacking optimal wording. 

As you move through the plugin, make tooltips pop up and pay attention to the directions.  If there is anything to alter or add so that it makes more sense please suggest the correction.

**Comment by thehabes** [comment]
Sure!

In "Choose Desired Tasks", hover over checkboxes or the title next to the checkbox.  

In "Consult Preferences", hover over the titles, like JP2 Compressor

Any short form version of a file name should be hoverable to produce its full path version in a tooltip.

I cannot think of any others off the top of my head.  If you notice a spot you wish you had a tooltip, it would be worth bringing that up.

**Comment by thanneken** [comment]
Found it under Choose Desired Tasks but not on Consult Preferences. On linux now. I can check on Windows at the end of the week.

**Comment by thehabes** [comment]
We have settled on the UI, though there is always a place for more of these.
