### ISSUE TITLE
HSH Parameter Defaulting Behavior

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/SpectralRTI_Toolkit#84]
if (hshOrder < 2 ) hshOrder = 3;
 if (hshThreads < 1 ) hshThreads = 16;

This information should somehow be supplied to the user when filling out their preferences so they know more about it.  When these changes are applied in the code, it will be written to their preferences file and they should know why.

**Comment by thanneken** [comment]
I think the default values should work for most users. If we ever implement modes for simple and advanced these would be in advanced. I could say more in the documentation. If you want to link to the documentation you could use: 
`http://jubilees.stmarytx.edu/spectralrtiguide/processing.html#firstrun`

**Comment by thehabes** [comment]
We have settled on the default behavior.
