### ISSUE TITLE
HSHFitter for Linux

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#88]
It turns out is is possible to compile hshfitter on Linux. It lacks the .exe extension, so the plugin says "Try Again" It would be good to support the Linux version by dropping the check for the .exe file extension.

**Comment by thanneken** [comment]
Similarly, webGLRtiMaker can be compiled for Linux. However, Linux care about caps and the plugin calls for webGLRTIMaker, should be webGLRtiMaker (lowercase ti).

**Comment by thanneken** [comment]
temporary workaround is:
`ln -s hshfitter hshfitter.exe`
and
`ln -s webGLRtiMaker webGLRTIMaker.exe`

**Comment by thanneken** [comment]
This is also an issue on MacOS. The hshfitter available lacks the .exe extension. The plugin should be open to a file that begins `hshfitter` with or without the extension, ignore case.

**Comment by thehabes** [comment]
I was able to smooth out the caps issue.

The check is now 
```java
String preferredFitterCheck = preferredFitter.toLowerCase();
if (preferredFitterCheck.endsWith("hshfitter.exe") || preferredFitterCheck.endsWith("hshfitter"))
```

**Comment by thanneken** [comment]
looks good
