### ISSUE TITLE
No need to create empty folders

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#90]
The plugin is creating folders named `PCA` and `Captures-Transmissive-Gamma`. 
I'm not sure there is ever a use case in which those folders would need to be automatically generated if they did not already exist (they are both input into the plugin, not output). I suspect the folder creation was added to prevent a fail elsewhere, but a check on "if directory exists" would be more elegant.

**Comment by thehabes** [comment]
OK, it will no longer create these by default.  A peek at the refactor shows this should not cause null pointers down the line.

**Comment by thanneken** [comment]
Checked, confirmed
