### ISSUE TITLE
Sorting of narrowband captures for Extended Spectrum

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#91]
I don't seem to get this problem but several users at the workshop had some extra work to do when they got to the prompt to classify narrowband captures into red, green, blue, and none for Extended Spectrum processing. It should be that the files are ordered from shortest to longest wavelength and classified into blue, green, and red for the first third, middle third, and last third. This should be automatic if the files are sorted alphabetically OR if they are sorted by creation time. It's possible MacOS or some of the users were throwing off the access time by doing something. Anyway, their sequence and classification was all wrong and they had to identify each file as appropriate to blue, green, or red. Perhaps the simplest path to uniformity is to enforce an alphabetic sort. That might backfire for wavelengths over 1000 (which should be red). I don't think it would be better to parse the filename and do a numeric sort because other systems might create different filenames. I'm more tempted to go by the index number at the end of the filename, but that too might vary.

**Comment by thehabes** [comment]
At all points where `listOfNarrowbandCaptures = narrow_band_dir.listFiles();` there is now a `Arrays.sort(listOfNarrowbandCaptures, NameFileComparator.NAME_COMPARATOR);`

**Comment by thanneken** [comment]
I never had this problem myself so I can't really check it, but the solution looks good and I'm sure I'll encounter more newbies before long.
