### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#92]
Rather than having an "advanced" and "simple" mode, I think it makes sense to have the de facto simple mode be to accept the default values unless the user understands what is being changed. Specifically... 

The "Adjust Brightness" default value should be the second one, to identify a region that defines black and white." 

The default for PCA method should be "generate and manually select two" (especially now that you have that great window that walks them through the slice deletion). 

I believe the macro would set defaults on "Choose Desired Tasks" based on what it found in the project directory. If no light position data is found that box would be checked. If "AccurateColorRTI" wasn't already found that would be checked, and so forth. Not a huge deal but saves clicks.

**Comment by thehabes** [comment]
OK, these defaults are now implemented.  I was also able to revive the original task default selection from the macro

**Comment by thanneken** [comment]
Looks good. I personally always check static raking and webrti, but that might be more than most users want.
